import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='#!' />
      </Head>
      <headers>header</headers>
      <main>
        <h1 className='text-3xl font-bold underline text-cyan-300 '>you</h1>
        <h1 className='text-3xl font-bold underline text-red-500 '>
          Hello world!
        </h1>
      </main>
      <footer>footer</footer>
    </>
  )
}
